version: '3'
services:
  treopim:
    build: ./
    volumes:
      - ./data/www:/var/www/html
      - ./data/logs/:/var/log/docker
    ports:
     - "8080:80"
    links:
     - "mysqldb"

  mysqldb:
    image: "mysql:5"
    ports:
     - "3306:3306"
    volumes:
     - ./data/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
