version: '3'
services:
  treopim:
    build: ./
    ports:
     - "8080:80"
    links:
     - "mysqldb"

  mysqldb:
    image: "mysql:5"
    ports:
     - "3306:3306"
    volumes: 
      - "./mysql_data:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=my-secret-pw"
    command: --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password
